name: build-and-test

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      # Clones to ${{ runner.workspace }}/pico_tree
      - uses: actions/checkout@v2

      - uses: actions/checkout@v2
        with:
          repository: google/googletest
          ref: release-1.8.1
          # For some reason in windows-latest we can only create directories within pico_tree/pico_tree.
          path: ${{ runner.workspace }}/pico_tree/googletest

      - name: Clone Eigen
        working-directory: ${{runner.workspace}}/pico_tree
        shell: bash
        run: |
          git clone https://gitlab.com/libeigen/eigen.git --branch 3.3.9 --depth 1 && cd eigen
          git switch -c 3.3.9

      - name: Create Build Environment
        shell: bash
        # Within the Windows environment the GITHUB_WORKSPACE variable uses a \ as a separator. MinGW cmake cannot handle this.
        # ${GITHUB_WORKSPACE//'\'/'/'} replaces \ with / using the bash shell.
        run: cmake -E make_directory ${GITHUB_WORKSPACE//'\'/'/'}/install

      - name: CMake Google Test
        uses: ./.github/actions/cmake
        with:
          path-cmake-lists: ${{ runner.workspace }}/pico_tree/googletest
          # 1) GTest is build statically but the CMake + Visual Studio combination wants to link against it as being dynamic.
          #    https://github.com/google/googletest/tree/release-1.8.1/googletest#visual-studio-dynamic-vs-static-runtimes
          # 2) The installation directory is customized so PicoTree knows where to find it later.
          cmake-configure-flags: -DCMAKE_INSTALL_PREFIX=${GITHUB_WORKSPACE//'\'/'/'}/install -Dgtest_force_shared_crt=ON
          cmake-install: true

      - name: CMake Eigen
        uses: ./.github/actions/cmake
        with:
          path-cmake-lists: ${{ runner.workspace }}/pico_tree/eigen
          cmake-configure-flags: -DCMAKE_INSTALL_PREFIX=${GITHUB_WORKSPACE//'\'/'/'}/install
          cmake-install: true

      - name: CMake PicoTree
        uses: ./.github/actions/cmake
        with:
          path-cmake-lists: ${{ runner.workspace }}/pico_tree
          cmake-configure-flags: -DCMAKE_PREFIX_PATH=${GITHUB_WORKSPACE//'\'/'/'}/install
          cmake-ctest: true
