name: pip

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      # Clones to ${{ github.workspace }}.
      - name: Clone PicoTree
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.6"

      # The GCC and MSVC compilers integrate OpenMP. Newer versions of CLang
      # integrate it as well, but it's not found via CMake on macos-latest.
      - name: Install OpenMP for macOS
        if: runner.os == 'macOS'
        run: brew install libomp

      # The global version of pybind11 allows us to find it via CMake.
      - name: Update setup related tools
        run: |
          python -m pip install --upgrade wheel setuptools
          pip install ninja
          pip install scikit-build
          pip install pybind11-global

      # Running the unit tests will fail without setting up the environment. 
      # The installed package or built module will not be found.
      # See example: https://github.com/pybind/scikit_build_example/blob/master/.github/workflows/pip.yml
      - name: Setting up compiler environment for Windows
        if: runner.os == 'Windows'
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Install with pip
        run: pip install ./ -v

      - name: Test Python bindings
        run: python -m unittest discover -s ./test/pyco_tree -p '*_test.py' -v
