name: pip

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      # Clones to ${{ runner.workspace }}/pico_tree
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: "3.5"

      - name: Install OpenMP for macOS
        if: runner.os == 'macOS'
        run: brew install llvm libomp

      # The global version of pybind11 allows us to find it via CMake.
      - name: Update setup related tools
        run: |
          python -m pip install --upgrade wheel setuptools
          pip install ninja
          pip install scikit-build
          pip install pybind11-global

      # Without this, running the unit tests will fail: The installed package
      # or built module will not be found.
      # See example: https://github.com/pybind/scikit_build_example/blob/master/.github/workflows/pip.yml
      - name: Prepare compiler environment for Windows
        if: runner.os == 'Windows'
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Install with pip
        working-directory: ${{runner.workspace}}
        run: pip install ./pico_tree -v

      - name: Test Bindings
        working-directory: ${{runner.workspace}}
        run: python -m unittest discover -s ./pico_tree/test/pyco_tree -p '*_test.py' -v
